In [1]:
import numpy as np
import pandas as pd

In [6]:
cands = pd.read_csv('../data/raw/cands22.txt', 
                    quotechar='|',
                    header=None)

In [7]:
cands

,0,1,2,3,4,5,6,7,8,9,10,11
0,2022,H0AK00105,N00039029,Thomas Lamb (3),3,AK01,,,,,3N,
1,2022,H0AL01055,N00044245,Jerry Carl (R),R,AL01,AL01,Y,Y,I,RW,
2,2022,H0AL01063,N00044288,Wes Lambert (R),R,AL01,,,,,RN,
3,2022,H0AL01097,N00044750,James Averhart (D),D,AL01,,,,,DN,
4,2022,H0AL02087,N00030768,Martha Roby (R),R,AL02,,,,,RN,
...,...,...,...,...,...,...,...,...,...,...,...,...
8923,2022,S8WI00224,N00041929,Leah Vukmir (R),R,WIS1,,,,,RN,
8924,2022,S8WV00119,N00041293,Paula Jean Swearengin (D),D,WVS2,,,,,DN,
8925,2022,S8WV00127,N00035531,Evan Jenkins (R),R,WVS1,,,,,RN,
8926,2022,S8WV00135,N00041474,Bo Copley (R),R,WVS1,,,,,RN,
8927,2022,S8WV00143,N00012642,Patrick Morrisey (R),R,WVS1,,,,,RN,

In [8]:
url = 'https://voteview.com/static/data/out/votes/HSall_votes.csv'

votes = pd.read_csv(url)

/var/folders/nb/2l1cxb_574d3h_kvyxmjyybw0000gp/T/ipykernel_24621/3249083044.py:3: DtypeWarning: Columns (0: prob) have mixed types. Specify dtype option on import or set low_memory=False.
  votes = pd.read_csv(url)

In [10]:
votes.head(3).T

                            0                 1                  2
congress                    1                 1                  1
chamber                 House             House              House
rollnumber                  1                 1                  1
icpsr                   154.0             259.0              379.0
cast_code                   6                 9                  1
prob        56.92195016659824  98.3120269302764  98.47231695715722

In [11]:
votes = votes.drop(columns=['prob'])

In [12]:
votes.dtypes

congress        int64
chamber           str
rollnumber      int64
icpsr         float64
cast_code       int64
dtype: object

In [13]:
votes.to_csv("../data/raw/allvotes.csv", index=False)

In [14]:
votes.to_parquet("../data/raw/allvotes.parquet", compression='zstd')

In [18]:
import os

In [15]:
votes_csv = pd.read_csv("../data/raw/allvotes.csv")

In [16]:
votes_parquet = pd.read_parquet("../data/raw/allvotes.parquet")

In [19]:
os.path.getsize("../data/raw/allvotes.csv")

608903352

In [20]:
os.path.getsize("../data/raw/allvotes.parquet")

9312586