In [1]:
import numpy as np
import pandas as pd

In [3]:
allvotes = pd.read_parquet('../data/raw/allvotes.parquet')
allvotes

          congress chamber  rollnumber    icpsr  cast_code
0                1   House           1    154.0          6
1                1   House           1    259.0          9
2                1   House           1    379.0          1
3                1   House           1    649.0          1
4                1   House           1    786.0          1
...            ...     ...         ...      ...        ...
26391744       119  Senate         891  42506.0          1
26391745       119  Senate         891  42507.0          1
26391746       119  Senate         891  42508.0          1
26391747       119  Senate         891  49308.0          6
26391748       119  Senate         891  49703.0          1

[26391749 rows x 5 columns]

In [4]:
committee_assignments = pd.read_parquet('../data/raw/committee_assignments.parquet')
committee_assignments

     committee_id bioguide_id                name     party     title  rank
0            SSAF     B001236        John Boozman  majority  Chairman     1
1            SSAF     M000355     Mitch McConnell  majority       NaN     2
2            SSAF     H001061         John Hoeven  majority       NaN     3
3            SSAF     E000295          Joni Ernst  majority       NaN     4
4            SSAF     H001079    Cindy Hyde-Smith  majority       NaN     5
...           ...         ...                 ...       ...       ...   ...
3890         HSQJ     C001130    Jasmine Crockett  minority       NaN     2
3891         HSQJ     H001077        Clay Higgins  majority       NaN     3
3892         HSQJ     M001217     Jared Moskowitz  minority       NaN     3
3893         HSQJ     N000026       Troy E. Nehls  majority       NaN     4
3894         HSQJ     H001096  Harriet M. Hageman  majority       NaN     5

[3895 rows x 6 columns]

In [6]:
crosswalk = pd.read_parquet('../data/raw/crosswalk.parquet')
crosswalk.head(3).T

,0,1,2
last_name,Cantwell,Klobuchar,Sanders
first_name,Maria,Amy,Bernard
middle_name,NaN,Jean,NaN
suffix,NaN,NaN,NaN
nickname,NaN,NaN,Bernie
full_name,Maria Cantwell,Amy Klobuchar,Bernard Sanders
birthday,1958-10-13,1960-05-25,1941-09-08
gender,F,F,M
type,sen,sen,sen
state,WA,MN,VT
district,NaN,NaN,NaN
senate_class,1.0,1.0,1.0
party,Democrat,Democrat,Independent
url,https://www.cantwell.senate.gov,https://www.klobuchar.senate.gov,https://www.sanders.senate.gov
address,511 Hart Senate Office Building Washington DC ...,425 Dirksen Senate Office Building Washington ...,332 Dirksen Senate Office Building Washington ...
phone,202-224-3441,202-224-3244,202-224-5141
contact_form,https://www.cantwell.senate.gov/public/index.c...,https://www.klobuchar.senate.gov/public/index....,https://www.sanders.senate.gov/contact/
rss_url,http://www.cantwell.senate.gov/public/index.cf...,NaN,http://www.sanders.senate.gov/rss/
twitter,SenatorCantwell,SenAmyKlobuchar,SenSanders
twitter_id,117501995.0,22044727.0,29442313.0
facebook,senatorcantwell,NaN,senatorsanders
youtube,SenatorCantwell,senatorklobuchar,senatorsanders
youtube_id,UCN52UDqKgvHRk39ncySrIMw,UCvdeJsDsV51tFb_hVqvtYGA,UCD_DaKNac0Ta-2PeHuoQ1uA
mastodon,NaN,NaN,NaN
bioguide_id,C000127,K000367,S000033
thomas_id,172.0,1826.0,1010.0
opensecrets_id,N00007836,N00027500,N00000528
lis_id,S275,S311,S313
fec_ids,"S8WA00194,H2WA01054",S6MN00267,"H8VT01016,S4VT00033"
cspan_id,26137.0,83701.0,994.0
govtrack_id,300018,412242,400357
votesmart_id,27122.0,65092.0,27110.0
ballotpedia_id,Maria Cantwell,Amy Klobuchar,Bernie Sanders
washington_post_id,NaN,NaN,NaN
icpsr_id,39310,40700,29147
wikipedia_id,Maria Cantwell,Amy Klobuchar,Bernie Sanders

In [8]:
ideology = pd.read_parquet('../data/raw/ideology.parquet')
ideology

,congress,chamber,icpsr,state_icpsr,district_code,state_abbrev,party_code,occupancy,last_means,bioname,...,died,nominate_dim1,nominate_dim2,nominate_log_likelihood,nominate_geo_mean_probability,nominate_number_of_votes,nominate_number_of_errors,conditional,nokken_poole_dim1,nokken_poole_dim2
0,119,President,99912,99,0,USA,200,0.0,0.0,"TRUMP, Donald John",...,NaN,0.403,0.162,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,119,House,20301,41,3,AL,200,NaN,NaN,"ROGERS, Mike Dennis",...,NaN,0.379,0.377,-13.62663,0.97596,560.0,5.0,NaN,0.398,0.396
2,119,House,21102,41,7,AL,100,NaN,NaN,"SEWELL, Terri",...,NaN,-0.402,0.397,-43.17652,0.92592,561.0,19.0,NaN,-0.410,0.452
3,119,House,21500,41,6,AL,200,NaN,NaN,"PALMER, Gary James",...,NaN,0.670,0.113,-39.51667,0.93268,567.0,21.0,NaN,0.539,-0.000
4,119,House,22140,41,1,AL,200,NaN,NaN,"MOORE, Barry",...,NaN,0.646,-0.240,-51.33822,0.91255,561.0,20.0,NaN,0.687,-0.206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,119,Senate,42504,56,0,WV,200,NaN,NaN,"JUSTICE, James Conley, II",...,NaN,0.563,0.297,-10.04553,0.98841,862.0,4.0,NaN,0.563,0.302
553,119,Senate,29940,25,0,WI,100,NaN,NaN,"BALDWIN, Tammy",...,NaN,-0.484,-0.123,-80.11412,0.91474,899.0,45.0,NaN,-0.387,-0.081
554,119,Senate,41111,25,0,WI,200,NaN,NaN,"JOHNSON, Ron",...,NaN,0.648,-0.162,-35.21822,0.96120,890.0,16.0,NaN,0.887,-0.128
555,119,Senate,20953,68,0,WY,200,NaN,NaN,"LUMMIS, Cynthia M.",...,NaN,0.682,-0.311,-33.09997,0.96275,872.0,12.0,NaN,0.870,0.242
556,119,Senate,40707,68,0,WY,200,NaN,NaN,"BARRASSO, John A.",...,NaN,0.540,0.196,-13.33774,0.98526,898.0,5.0,NaN,0.650,0.397

In [11]:
independent_expenditures = pd.read_parquet('../data/raw/independent_expenditures.parquet')
independent_expenditures

,candidate_id,candidate_name,committee_id,committee_name,count,cycle,support_oppose_indicator,total
0,H0AZ01259,"GOSAR, PAUL DR.",C00552851,FREEDOM CAUCUS FUND,40,2026,S,784.11
1,H0CA03078,"BERA, AMERISH",C00640300,ACTIVATE AMERICA,1,2026,S,771.08
2,H0CA08135,"OBERNOLTE, JAY",C00892653,WORKING CLASS HEROES FUND,1,2026,O,18689.58
3,H0CA08135,"OBERNOLTE, JAY",C00916692,AMERICAN MISSION,1,2026,S,259682.32
4,H0CA10073,"DESAULNIER, MARK",C00483693,SIERRA CLUB INDEPENDENT ACTION,1,2026,S,10.00
...,...,...,...,...,...,...,...,...
986,S8MS00261,"HYDE-SMITH, CINDY",C00748582,REALLY AMERICAN PAC,3,2026,O,612.50
987,S8MS00261,"HYDE-SMITH, CINDY",C00814202,NEW SOUTHERN MAJORITY IE PAC,12,2026,O,77047.74
988,S8MS00261,"HYDE-SMITH, CINDY",C00850487,CONSERVATIVE LEADERS OF AMERICA,5,2026,S,133948.39
989,S8OR00207,"MERKLEY, JEFFREY ALAN",C00489799,PLANNED PARENTHOOD VOTES,1,2026,S,8.67
990,S8OR00207,"MERKLEY, JEFFREY ALAN",C00802389,GIVEGREEN UNITED ACTION,2,2026,S,120.00

In [71]:
member_details = pd.read_parquet('../data/raw/member_details.parquet')
member_details.head(3).T

,0,1,2
bioguideId,W000832,B001328,G000607
birthYear,1987,1992,1981
currentMember,True,True,True
directOrderName,Aisha Wahab,Everton Blair Jr.,James Gallagher
district,14.0,13.0,1.0
firstName,Aisha,Everton,James
honorificName,Ms.,Mr.,Mr.
invertedOrderName,"Wahab, Aisha","Blair, Everton","Gallagher, James"
lastName,Wahab,Blair,Gallagher
officialWebsiteUrl,https://wahab.house.gov/,https://blair.house.gov/,https://gallagher.house.gov
partyHistory,"[{'partyAbbreviation': 'D', 'partyName': 'Demo...","[{'partyAbbreviation': 'D', 'partyName': 'Demo...","[{'partyAbbreviation': 'R', 'partyName': 'Repu..."
previousNames,"[{'directOrderName': 'Aisha Wahab', 'firstName...","[{'directOrderName': 'Everton Blair Jr.', 'fir...","[{'directOrderName': 'James Gallagher', 'first..."
state,California,Georgia,California
terms,"[{'chamber': 'House of Representatives', 'cong...","[{'chamber': 'House of Representatives', 'cong...","[{'chamber': 'House of Representatives', 'cong..."
updateDate,2026-09-29T07:40:27Z,2026-09-29T07:40:27Z,2026-09-29T07:40:27Z
addressInformation.city,Washington,Washington,Washington
addressInformation.district,DC,DC,DC
addressInformation.officeAddress,174 Cannon House Office Building,468 Cannon House Office Building,408 Cannon House Office Building
addressInformation.phoneNumber,(202) 225-5065,(202) 225-2939,(202) 225-3076
addressInformation.zipCode,20515.0,20515.0,20515.0
cosponsoredLegislation.count,2,21,57
cosponsoredLegislation.url,https://api.congress.gov/v3/member/W000832/cos...,https://api.congress.gov/v3/member/B001328/cos...,https://api.congress.gov/v3/member/G000607/cos...
depiction.attribution,Image courtesy of the Member,Image courtesy of the Member,NaN
depiction.imageUrl,https://www.congress.gov/img/member/6a986b632a...,https://www.congress.gov/img/member/6a9869d92a...,https://www.congress.gov/img/member/6a29d4f81c...
suffixName,NaN,Jr.,NaN
sponsoredLegislation.count,NaN,1.0,7.0
sponsoredLegislation.url,NaN,https://api.congress.gov/v3/member/B001328/spo...,https://api.congress.gov/v3/member/G000607/spo...
middleName,NaN,NaN,NaN
nickName,NaN,NaN,NaN
leadership,None,None,None
deathYear,NaN,NaN,NaN

In [10]:
members = pd.read_parquet('../data/raw/members.parquet')
members

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14.0,"Wahab, Aisha",Democratic,California,2026-09-29T07:40:27Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13.0,"Blair, Everton",Democratic,Georgia,2026-09-29T07:40:27Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1.0,"Gallagher, James",Republican,California,2026-09-29T07:40:27Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11.0,"Mejia, Analilia",Democratic,New Jersey,2026-09-29T07:40:27Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14.0,"Fuller, Clay",Republican,Georgia,2026-09-29T07:40:27Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
...,...,...,...,...,...,...,...,...,...,...
550,C001078,11.0,"Connolly, Gerald E.",Democratic,Virginia,2025-05-21T13:36:20Z,https://api.congress.gov/v3/member/C001078?for...,Image courtesy of the Member,https://www.congress.gov/img/member/c001078_20...,"[{'chamber': 'House of Representatives', 'star..."
551,G000551,7.0,"Grijalva, Raúl M.",Democratic,Arizona,2025-03-28T15:05:08Z,https://api.congress.gov/v3/member/G000551?for...,Image courtesy of the Member,https://www.congress.gov/img/member/g000551_20...,"[{'chamber': 'House of Representatives', 'star..."
552,T000489,18.0,"Turner, Sylvester",Democratic,Texas,2025-03-05T16:51:50Z,https://api.congress.gov/v3/member/T000489?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745fdc0b...,"[{'chamber': 'House of Representatives', 'star..."
553,R000595,NaN,"Rubio, Marco",Republican,Florida,2025-01-21T16:11:29Z,https://api.congress.gov/v3/member/R000595?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/r000595_20...,"[{'chamber': 'Senate', 'startYear': 2011, 'end..."
554,V000137,NaN,"Vance, J. D.",Republican,Ohio,2025-01-10T15:23:00Z,https://api.congress.gov/v3/member/V000137?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/v000137_20...,"[{'chamber': 'Senate', 'startYear': 2023, 'end..."

In [12]:
sponsored_legislation = pd.read_parquet('../data/raw/sponsored_legislation.parquet')
sponsored_legislation

,congress,introducedDate,number,title,type,url,latestAction.actionDate,latestAction.text,policyArea.name,sponsor_bioguide_id,amendmentNumber,latestAction.actionTime,latestAction
0,119,2026-09-24,10533,Newton County Water Infrastructure Improvement...,HR,https://api.congress.gov/v3/bill/119/hr/10533?...,2026-09-24,Referred to the House Committee on Transportat...,NaN,B001328,NaN,NaN,NaN
1,119,2026-09-08,10304,Drone Safety Statement Modernization Act,HR,https://api.congress.gov/v3/bill/119/hr/10304?...,2026-09-15,Ordered to be Reported (Amended) by Voice Vote.,Transportation and Public Works,G000607,NaN,NaN,NaN
2,119,2026-08-27,10154,Protect America from CARB Act of 2026,HR,https://api.congress.gov/v3/bill/119/hr/10154?...,2026-08-27,Referred to the House Committee on Energy and ...,Environmental Protection,G000607,NaN,NaN,NaN
3,119,2026-08-13,10089,Representation Act,HR,https://api.congress.gov/v3/bill/119/hr/10089?...,2026-08-13,Referred to the House Committee on the Judiciary.,Government Operations and Politics,G000607,NaN,NaN,NaN
4,119,2026-08-10,213,Providing for congressional disapproval under ...,HJRES,https://api.congress.gov/v3/bill/119/hjres/213...,2026-09-17,Received in the Senate.,Environmental Protection,G000607,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
128883,118,2023-07-19,2374,No Obamacare for Illegal Aliens Act,S,https://api.congress.gov/v3/bill/118/s/2374?fo...,2023-09-05,Star Print ordered on the bill.,Health,V000137,NaN,NaN,NaN
128884,118,2024-01-25,3668,State Border Security Act,S,https://api.congress.gov/v3/bill/118/s/3668?fo...,2024-01-25,Read twice and referred to the Committee on th...,Immigration,V000137,NaN,NaN,NaN
128885,118,2024-01-23,3638,Dependent Controlled Substance Transparency Act,S,https://api.congress.gov/v3/bill/118/s/3638?fo...,2024-01-23,Read twice and referred to the Committee on He...,Health,V000137,NaN,NaN,NaN
128886,118,2023-05-11,26,A joint resolution disapproving the action of ...,SJRES,https://api.congress.gov/v3/bill/118/sjres/26?...,2023-05-11,Read twice and referred to the Committee on Ho...,Government Operations and Politics,V000137,NaN,NaN,NaN
128887,118,2023-03-30,1109,English Language Unity Act of 2023,S,https://api.congress.gov/v3/bill/118/s/1109?fo...,2023-03-30,Read twice and referred to the Committee on Ho...,Government Operations and Politics,V000137,NaN,NaN,NaN

In [13]:
votes = pd.read_parquet('../data/raw/votes.parquet')
votes

        congress chamber  rollnumber  icpsr  cast_code   prob
0            119   House           1  14854          1   99.6
1            119   House           1  14863          1   78.9
2            119   House           1  14873          6  100.0
3            119   House           1  15029          6  100.0
4            119   House           1  15433          6  100.0
...          ...     ...         ...    ...        ...    ...
382426       119  Senate         909  42506          1   96.3
382427       119  Senate         909  42507          1   95.1
382428       119  Senate         909  42508          1   99.5
382429       119  Senate         909  49308          1   54.9
382430       119  Senate         909  49703          1   95.3

[382431 rows x 6 columns]

In [14]:
allvotes

          congress chamber  rollnumber    icpsr  cast_code
0                1   House           1    154.0          6
1                1   House           1    259.0          9
2                1   House           1    379.0          1
3                1   House           1    649.0          1
4                1   House           1    786.0          1
...            ...     ...         ...      ...        ...
26391744       119  Senate         891  42506.0          1
26391745       119  Senate         891  42507.0          1
26391746       119  Senate         891  42508.0          1
26391747       119  Senate         891  49308.0          6
26391748       119  Senate         891  49703.0          1

[26391749 rows x 5 columns]

In [32]:
list_of_lists = [x.split(',') for x in crosswalk['fec_ids'] if pd.notnull(x)]
fec_list = [item for sublist in list_of_lists for item in sublist]
fec_list

['S8WA00194',
 'H2WA01054',
 'S6MN00267',
 'H8VT01016',
 'S4VT00033',
 'S6RI00221',
 'S6WY00068',
 'H4MS01078',
 'S8MS00196',
 'S6ME00159',
 'S2TX00106',
 'S6IL00151',
 'H2IL20026',
 'S2KY00012',
 'S8OR00207',
 'S6RI00163',
 'H0RI02071',
 'S8ID00092',
 'S0NH00219',
 'S6VA00093',
 'P80003023',
 'H6NY20167',
 'S0NY00410',
 'S0DE00092',
 'H6AL04098',
 'H8WI00018',
 'S2WI00219',
 'S0CO00211',
 'H6FL09070',
 'H2GA02031',
 'H2TN06030',
 'S8TN00337',
 'S0CT00177',
 'H2AR03176',
 'S0AR00150',
 'H6FL13148',
 'H2CA37023',
 'H0WV02138',
 'S4WV00159',
 'H8IN07184',
 'H2TX31044',
 'H8LA00017',
 'S4LA00107',
 'H6FL11126',
 'H6FL11134',
 'H0CA32101',
 'H4NY11138',
 'H4MO05234',
 'H2SC02042',
 'H6TN09068',
 'H2OK04055',
 'H4CA20082',
 'H2CT02112',
 'S8ID00027',
 'H2ID02034',
 'H0AR01083',
 'H2TX23082',
 'H4IL07037',
 'H6CO01141',
 'H0CT03072',
 'H0TN04195',
 'H2FL25018',
 'H4TX10028',
 'H0TN03254',
 'H4NC05146',
 'H0CA10149',
 'H0AZ01259',
 'S0IA00028',
 'H0MO06073',
 'H4TX09095',
 'H0VA09055',
 'H8KY02031',
 'H8MD01094',
 'H8NM01224',
 'S2NM00088',
 'H8CT04172',
 'H6HI02251',
 'S2HI00106',
 'S0ND00093',
 'H2MD05155',
 'H0MI02094',
 'H6GA04129',
 'S0WI00197',
 'H6OH04082',
 'H2OH09031',
 'H0MA10082',
 'H0PA03271',
 'H0OK05114',
 'S4OK00232',
 'H0WA02080',
 'H8CT01046',
 'H8OH05036',
 'S0UT00165',
 'H4CA16049',
 'H4OK06056',
 'H8NM03196',
 'S0NM00058',
 'H2MA09072',
 'S0MA00083',
 'H6MA07101',
 'S4MA00028',
 'H6CA05195',
 'H4TX10093',
 'H8CA04152',
 'H6CA21135',
 'H0MN04049',
 'H4MA03022',
 'H8NY06048',
 'H4WI04183',
 'H6KS01096',
 'S0KS00091',
 'S4AK00099',
 'H6CT05124',
 'S2CT00132',
 'S2WA00189',
 'H2NY17071',
 'H8MA02041',
 'H0DC00058',
 'H8NJ03073',
 'S6NJ00263',
 'S0KY00156',
 'H8CA05035',
 'H8MI09068',
 'S4MI00355',
 'H8ME01120',
 'S0ME00038',
 'H0IL05096',
 'H0KY05015',
 'H2AL03032',
 'H0LA01087',
 'H8IL09067',
 'H0CA27085',
 'S4CA00555',
 'S8NY00082',
 'H0NY16010',
 'H4AZ06045',
 'H8AZ05097',
 'H0GA08099',
 'H6VA01117',
 'H0SC01279',
 'S4SC00240',
 'H0AL07086',
 'H6CA24113',
 'H8ID02064',
 'H6WA09025',
 'H6NE03115',
 'H8NJ04014',
 'H2CA39078',
 'H4MS02068',
 'H8CA01109',
 'H8PA05071',
 'S2SD00068',
 'H6SD00085',
 'H8NY21203',
 'H2OH03067',
 'H2OH03091',
 'H2MD08126',
 'S6MD03441',
 'H2NY00010',
 'H4MI07103',
 'H4FL20023',
 'H4CA23011',
 'H0FL08208',
 'S4FL00256',
 'H6VT00160',
 'H8VT00034',
 'S2VT00235',
 'H2SC02059',
 'H0FL17068',
 'H8VA01147',
 'H0AR03055',
 'S6OR00110',
 'H0OR03026',
 'H0IN09070',
 'S6IN00191',
 'H2NV02395',
 'H1NV02017',
 'S0NV00237',
 'H2OR01133',
 'H0WA08046',
 'H2KY04121',
 'S4HI00136',
 'H6HI02244',
 'H8IL14067',
 'H2IL11124',
 'H8NV03036',
 'H2AR04083',
 'S4AR00103',
 'H2CA06259',
 'H0CA03078',
 'H2CA00120',
 'H2CA36439',
 'H2CA43245',
 'H2CA50026',
 'H2CA52089',
 'H2FL14053',
 'H2FL22080',
 'H6IL06141',
 'S6IL00292',
 'H0KY06104',
 'S6KY00286',
 'S2MA00170',
 'S2ME00109',
 'H2MO02102',
 'H2MT01060',
 'S2MT00096',
 'H2NC08185',
 'H0ND01026',
 'H6ND00074',
 'S8ND00120',
 'S2NE00094',
 'H2NY06116',
 'H2NY10092',
 'H2OH03125',
 'H2OH14064',
 'H2PA04135',
 'S2TX00312',
 'H2TX14149',
 'H2TX35011',
 'H2TX33040',
 'S2TX00270',
 'H2TX33073',
 'S2VA00142',
 'H2WI02124',
 'H2IL02172',
 'S6IL00474',
 'H4MO08162',
 'S4NJ00185',
 'H4MA05084',
 'H4NJ01084',
 'H4NC12100',
 'H4AL06098',
 'H4AR02141',
 'H4AR04048',
 'H4AZ07043',
 'S4AZ00139',
 'H0CA10073',
 'H2CA31125',
 'H4CA33119',
 'H4CA35031',
 'H4GA01039',
 'S6GA00374',
 'H4GA11061',
 'H2GA12121',
 'H4IL12060',
 'H4MA06090',
 'S6MA00296',
 'H4MI04126',
 'H4MI12079',
 'H4MN06087',
 'H2NC07096',
 'H4NJ12149',
 'H4NY21079',
 'H4PA13199',
 'H6TX02079',
 'H4VA08224',
 'H2VI00082',
 'H4WA04104',
 'H4WI06048',
 'H4AS00036',
 'S4AK00214',
 'S4IA00129',
 'S4NC00162',
 'S4SD00049',
 'H6MS01131',
 'H6IL18088',
 'H6OH08315',
 'H6KY01110',
 'H6PA02171',
 'S4LA00065',
 'S6NH00091',
 'S6NV00200',
 'H2IL10068',
 'H6AZ05083',
 'H4CA12055',
 'H6CA20152',
 'H6CA24303',
 'H6CA44103',
 'H6CA46116',
 'H6DE00206',
 'S4DE00060',
 'H6FL02208',
 'H6FL04105',
 'H6FL09179',
 'H6FL18097',
 'H6IL08147',
 'S6IL00482',
 'H6IN03229',
 'S4IN00196',
 'H6KS01179',
 'S0KS00315',
 'H6LA03148',
 'H6LA04138',
 'H6MD08457',
 'H6MI01226',
 'H6NC13129',
 'S2NC00505',
 'H6NE02125',
 'H6NJ05171',
 'H6NV03139',
 'S8NV00156',
 'H2NY13096',
 'H6PA08277',
 'H6PA16320',
 'H2TN07103',
 'H6TX15162',
 'H6TX19099',
 'H6WA07458',
 'H8KS04112',
 'H8SC05158',
 'S6SC04445',
 'H8CA34266',
 'H8UT03238',
 'S4UT00282',
 'S8MN00578',
 'S8MS00261',
 'H8TX27049',
 'H8OH12180',
 'H8OK01157',
 'S6OK04247',
 'H8NY25105',
 'H8PA07200',
 'H2HI02128',
 'H2NV04011',
 'H8AZ09040',
 'H8CA10126',
 'H8CA49058',
 'H8CO02160',
 'H8CO06229',
 'H8CT05245',
 'H8FL17053',
 'H8GA06393',
 'H8ID01124',
 'H8IL04134',
 'H8IL06139',
 'H8IL14174',
 'H8IN04199',
 'H8KS03155',
 'H8MA03106',
 'H8MA07032',
 'H8MI08102',
 'S4MI00470',
 'H8MI11254',
 'S6MI00426',
 'H8MI13250',
 'H6MN02131',
 'S6MN00499',
 'H8MN05239',
 'H8MN08043',
 'H8MS03125',
 'H8NH01210',
 'S6NH00141',
 'H8NJ02166',
 'H8NJ03206',
 'S4NJ00466',
 'H6NV04020',
 'H8NY15148',
 'H8PA04116',
 'H8PA06087',
 'H8PA10147',
 'H8PA13125',
 'H8PA18199',
 'H8SC04250',
 'H8SD01055',
 'H8TN02119',
 'H8TN06094',
 'H8TX02166',
 'H8TX05144',
 'H8TX07140',
 'H8TX16109',
 'H8TX21307',
 'H8TX29052',
 'H8VA06104',
 'H8WA08189',
 'H8WI01156',
 'H8WV03097',
 'S8FL00273',
 'S8MO00160',
 'H8ME02185',
 'H0NC03172',
 'S6MD03185',
 'H6MD07020',
 'H0MD07114',
 'H0WI07101',
 'S0AZ00350',
 'H8WY00148',
 'S0WY00137',
 'H0CA48024',
 'S8CA00135',
 'H2TX03126',
 'H2CA20094',
 'S0AL00230',
 'S0CO00575',
 'S0TN00169',
 'H8AL02171',
 'S6AL00476',
 'H0CA08135',
 'H8CA39240',
 'H8CA49074',
 'H0CO03165',
 'H0FL03175',
 'H0FL15104',
 'H2FL14186',
 'H0FL26036',
 'H8FL27185',
 'H0GA05301',
 'H0GA09246',
 'H0IA01174',
 'H8IA02043',
 'H0IA04145',
 'H0IL15129',
 'H0IN01150',
 'H0IN05326',
 'H0KS01123',
 'H0MA04192',
 'H0MI10287',
 'H0MN07091',
 'H0NC02125',
 'H0NM03102',
 'H0NY02234',
 'H0NY11078',
 'H0NY15160',
 'H0OK05205',
 'H0OR02127',
 'H0SC01394',
 'H0TN01118',
 'H0TX04219',
 'H0TX11230',
 'H0TX13228',
 'H0TX22302',
 'H0TX24209',
 'H0UT01205',
 'H0UT04076',
 'H0WA10034',
 'H0WI05113',
 'S2CA00955',
 'H8GA06195',
 'S8GA00180',
 'S0GA00559',
 'H4NY22051',
 'H2LA05126',
 'S6LA00664',
 'H2LA02149',
 'H2NM01144',
 'H8TX06266',
 'H2OH11169',
 'H2OH15228',
 'H2NE01118',
 'H2MN01223',
 'H8NY19223',
 'H2IN02295',
 'H4MT01041',
 'S2AL00145',
 'S2MO00544',
 'S6PA00274',
 'H2AL05102',
 'H2AZ01354',
 'H2AZ02360',
 'H2CA03157',
 'H2CA14162',
 'H2CA37304',
 'H2CA47188',
 'H8CO07045',
 'H2FL04211',
 'H2FL07156',
 'H2FL10259',
 'H0FL13158',
 'H2FL15241',
 'H2FL22171',
 'H0GA07273',
 'H4GA10071',
 'S6GA00390',
 'H2GU01031',
 'H2HI02581',
 'H2IA03119',
 'H2IL01349',
 'H2IL03162',
 'H2IL13153',
 'H2IL17147',
 'H6IN09143',
 'H2KY03206',
 'H2MD04315',
 'H2MD04232',
 'H0MI03316',
 'H2MI10150',
 'S8MI00372',
 'H2MI13204',
 'H2MO04207',
 'H2MO07143',
 'H2MS04258',
 'H2NC02287',
 'H2NC06114',
 'H2NC14050',
 'H0NJ07261',
 'H2NJ08232',
 'H2NM02191',
 'H2NY01190',
 'H2NY10308',
 'H2NY17162',
 'H2NY23228',
 'H2OH01194',
 'H2OH16051',
 'H2OH13264',
 'H2OK02315',
 'H2OR04095',
 'H2OR06066',
 'H2PA18200',
 'H2PA17103',
 'H2RI02184',
 'H2SC07280',
 'S6SC04403',
 'H2TN05446',
 'H2TX01112',
 'H2TX03290',
 'H2TX00064',
 'H2TX08182',
 'H0TX15124',
 'H2TX30178',
 'S6TX00552',
 'H2TX35144',
 'H0TX07170',
 'S6TX00511',
 'H2VA02064',
 'H2VT01076',
 'H2WA03217',
 'H0WI03175',
 'H2WY00166',
 'S6WY00209',
 'S6NE00129',
 'H4VA04066',
 'H4RI01265',
 'H4UT02296',
 'H6NY03247',
 'H4NY26078',
 'H4CA20181',
 'H4OH06165',
 'H4NJ10176',
 'H4WI08119',
 'H4LA06211',
 'H0IN03198',
 'S0IN00095',
 'H8CA39174',
 'H4CA31170',
 'S4MD00327',
 'S4MT00183',
 'S4OH00192',
 'S2PA00661',
 'H2AK01083',
 'H4AL02170',
 'H4AZ03109',
 'H4AZ08108',
 'H4CA12154',
 'H2CA13115',
 'H4CA16197',
 'H4CA27111',
 'H4CA29141',
 'H4CA30149',
 'H4CA45170',
 'H4CA47085',
 'H4CO03357',
 'H6CO05142',
 'H4CO08034',
 'H4DE00045',
 'H4FL08168',
 'H4GA03126',
 'H4IN06185',
 'H4IN08249',
 'H4KS02164',
 'H4MD02232',
 'H4MD03156',
 'H4MD06340',
 'H2MI07123',
 'H4MI08218',
 'H4MN03118',
 'H4MO01134',
 'S4MO00250',
 'H8MO09146',
 'H4MO03221',
 'H4MP01022',
 'H4MT02098',
 'H4NC06177',
 'H6NC09200',
 'H4NC08066',
 'H2NC13243',
 'H4NC13116',
 'H4NC14015',
 'H4ND00061',
 'H4NH02399',
 'H4NJ03080',
 'H4NJ09194',
 'H4NY04158',
 'H2NY04244',
 'H4NY16087',
 'H8NY22177',
 'H4NY22085',
 'H4OH02248',
 'H4OR03192',
 'H4OR05304',
 'H8PA15195',
 'H4PA08124',
 'H4PR01010',
 'H4SC01313',
 'H4TX12065',
 'H4TX26149',
 'H4TX32089',
 'H4UT03260',
 'H2VA07196',
 'H0VA07133',
 'H4VA07234',
 'H4VA10279',
 'H4WA05234',
 'H4WA06117',
 'H4WV02205',
 'S4WV00332',
 'S6OH00304',
 'S6FL00640',
 'H6FL01390',
 'H6FL06258',
 'H6VA11066',
 'H6AZ07121',
 'H6TN07161',
 'H6TX18232',
 'H0GA14030',
 'H6NJ11286',
 'H6CA01285',
 'H6GA13062',
 'H0CA15213']

In [31]:
import dotenv
import os
import requests
dotenv.load_dotenv()
FEC_API_KEY = os.getenv('FEC_API_KEY')
botname = 'contrans'
version = '2026'
website = 'https://github.com/jkropko/contrans2026'
email = 'jkropko@virginia.edu'
useragent = f'{botname}/{version} ({website}; {email}) python-requests/{requests.__version__}'
headers = {'User-Agent': useragent}

In [70]:
root = 'https://api.open.fec.gov'
endpoint = '/v1/schedules/schedule_e'
fec_results_list = []

params = {'api_key': FEC_API_KEY,
          'candidate_id': fec_list[20],
          'per_page': 100,
          'cycle': '2026'}

newresults = 1
while newresults > 0:
    r = requests.get(root + endpoint, params = params, headers = headers)
    print(r.json())
    newresults_list = r.json()['results']
    newresults = len(newresults_list)
    fec_results_list.extend(newresults_list)
    if newresults > 0:
        params['last_expenditure_date'] = r.json()['pagination']['last_indexes']['last_expenditure_date']
        params['last_index'] = r.json()['pagination']['last_indexes']['last_index']

{'api_version': '1.0', 'pagination': {'count': 0, 'is_count_exact': True, 'last_indexes': None, 'pages': 0, 'per_page': 100}, 'results': []}

In [65]:
fec_results_list

[]